# Generated by Django 4.2.26 on 2025-11-24 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PredictionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="predictions/")),
                ("predicted_class", models.CharField(max_length=50)),
                ("confidence", models.FloatField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "Prediction Histories",
                "ordering": ["-timestamp"],
            },
        ),
    ]
